name: keep function warm

on:
  schedule:
    - cron:  '*/8 * * * *'

jobs:
  ping:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        CURL_URL: ${{ secrets.CURL_URL }}
      run: |
        curl --silent --show-error --fail "$CURL_URL"
