name: keep melon.sh warm

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  ping:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - run: curl --silent --show-error --fail https://melon.sh
